// Liste des fichiers dans frontend/public/images/
// Mettez à jour ce tableau quand vous ajoutez ou renommez des images.
// Le nom affiché sous l'image = nom du fichier sans l'extension.

const stripImages: string[] = [
  'Mug.png',
  'Cartes Visites.png',
  'Casquettes.png',
  '4.png',
  'Hoodies.png',
  '6.png',
  '7.png',
  '8.png',
  '9.png',
  '10.png',
  'Stickers.png',
  '12.png',
  '13.png',
  '14.png',
  '15.png',
  '16.png',
  "T'Shirts.png",
  '18.png',
  '19.png',
  '20.png',
  '21.png',
  '22.png',
  '23.png',
  '24.png',
  '25.png',
  '26.png',
  '27.png',
  '28.png',
  '29.png',
  '30.png',
  '31.png',
  '32.png',
  '33.png',
  '34.png',
  '35.png',
  '36.png',
  '37.png',
  '38.png',
  '39.png',
  '40.png',
  '41.png',
  '42.png',
  '43.png',
  'Tapis de Souris.png',
];

export default stripImages;
